### PR TITLE
Fix Cisco Packet Tracer ebuild

### PR DESCRIPTION
**Pull request by r4rdsn**
- Add libressl support with libressl USE flag
- Change default DISTDIR to /var/cache/distfiles

### CODE REVIEW

**Comment by r4rdsn** [comment]
why?

**Comment by jorgicio** [comment]
Hi, sorry, I just watched this today. I renamed the branch to "main" so "master" branch is not available anymore.

**Comment by jorgicio** [comment]
Changes are done manually from what you sent. Thanks!

**Comment by r4rdsn** [comment]
alright, I was going to send another PR to main but wanted to make sure that everything else is OK first.

**Pull request closed without merging**
